language: python
dist: xenial
python:
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - chmod +x manage.py

install:
  - pip install -r requirements.txt

script:
    - SECRET_KEY="whatever" ./manage.py test
